### ISSUE TITLE
Usage on Windows

### ISSUE THREAD

**Issue by ctrl-Felix** [cpcloud/protoletariat#386]
I currently am not able to make it work on Windows. However it works in the WSL shell with the same syntax. I keep getting a ``FileNotFoundError: [WinError 2]`` on Windows. Am I doing something wrong with the syntax?

This one is not working:
```
protol --create-package --in-place --python-out=cosmospy_protobuf protoc --proto-path=C:\Users\felix\Documents\dev\cosmospy-protobuf\cosmospy_protobuf  C:\Users\felix\Documents\dev\cosmospy-protobuf\cosmospy_protobuf\gogoproto\gogo.proto
```

This one is working:
```
protol --create-package --in-place --python-out=cosmospy_protobuf protoc --proto-path=/mnt/c/Users/felix/Documents/dev/cosmospy-protobuf/cosmospy_protobuf  /mnt/c/Users/felix/Documents/dev/cosmospy-protobuf/cosmospy_protobuf/gogoproto/gogo.proto
```

Same behaviour when using ``subprocess.run()`` in a .py file:
```python
absolute_path = os.path.abspath('cosmospy_protobuf')

#Genrated in a loop but this is how the path is generated
os.path.abspath(os.path.join(root, filename)

cmd = [sys.executable, '-m', 'protoletariat',
           '--create-package', '--in-place',
           '--python-out', 'cosmospy_protobuf',
           'protoc', f'--proto-path={absolute_path}',
           filepath]
subprocess.run(cmd)
   ```
   This works on Linux but not on windows

**Comment by cpcloud** [comment]
@ctrl-Felix Can you show the full traceback from `FileNotFoundError: [WinError 2]`?

**Comment by ctrl-Felix** [comment]
Of course
```Traceback (most recent call last):
  File "C:\Users\felix\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\felix\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\felix\Documents\dev\cosmospy-protobuf\venv\Scripts\protol.exe\__main__.py", line 7, in <module>
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\protoletariat\__main__.py", line 145, in protoc
    Protoc(
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\protoletariat\fdsetgen.py", line 67, in fix_imports
    fdset = FileDescriptorSet.FromString(self.generate_file_descriptor_set_bytes())
  File "c:\users\felix\documents\dev\cosmospy-protobuf\venv\lib\site-packages\protoletariat\fdsetgen.py", line 137, in generate_file_descriptor_set_bytes
    subprocess.check_output(
  File "C:\Users\felix\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\felix\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\felix\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\felix\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by cpcloud** [comment]
@ctrl-Felix Does using

```
 fr'--proto-path={absolute_path}'
```

address the issue?

Meanwhile, I'm trying to get Windows CI going using powershell instead of bash, which should help reproduce the problem.

**Comment by cpcloud** [comment]
@ctrl-Felix Do you know which file cannot be found?

**Comment by ctrl-Felix** [comment]
No. I have to admit I am not really able to say what's going wrong there. I have a couple of folders in my folder structure on 4 levels I think but the error log isn't really helping me to understand what's wrong. 

Couldn't you reproduce it?

**Comment by cpcloud** [comment]
@ctrl-Felix Can you change just one of the `C:\`-style paths to `/mnt/c` at a time and rule each one out as the problem?

**Comment by ctrl-Felix** [comment]
How exactly should that work?. C:\ is for windows and /mnt/c on WSL. Or am I getting something wron with the goal here

**Comment by cpcloud** [comment]
> How exactly should that work?. C:\ is for windows and /mnt/c on WSL. Or am I getting something wron with the goal here

Sorry, I didn't realize the second one was WSL.

It kind of looks like for whatever reason the `protoc` executable cannot be found on windows. Can you confirm that `protoc` can be invoked using `subprocess.run` on Windows?

**Comment by ctrl-Felix** [comment]
You're right. I didn't think about that but protoc can't be invoked. Especially as I am using the python package grpc_tools.protoc to compile my proto files

**Comment by ctrl-Felix** [comment]
Actually, wouldn't it me possible to add this one as a dependency and use it then to avoid having to install protoc separately. I prefer grpc_tools.protoc as I can get the grpc files there too. It's part of the grpc-tools package

**Comment by cpcloud** [comment]
@ctrl-Felix Did you get a chance to figure this out?

**Comment by ctrl-Felix** [comment]
It seems like it was the path issue. Thank you veryy much for helping and creating this super useful tool!
I nearly gave up before finding this
